/*
 * This file is generated by jOOQ.
 */
package com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankTransactionClassification implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long bankTransactionId;
    private final String categoryFiftyThirtyTwenty;
    private final String categoryDetailed;
    private final String comment;

    public BankTransactionClassification(BankTransactionClassification value) {
        this.id = value.id;
        this.bankTransactionId = value.bankTransactionId;
        this.categoryFiftyThirtyTwenty = value.categoryFiftyThirtyTwenty;
        this.categoryDetailed = value.categoryDetailed;
        this.comment = value.comment;
    }

    public BankTransactionClassification(
        Long id,
        Long bankTransactionId,
        String categoryFiftyThirtyTwenty,
        String categoryDetailed,
        String comment
    ) {
        this.id = id;
        this.bankTransactionId = bankTransactionId;
        this.categoryFiftyThirtyTwenty = categoryFiftyThirtyTwenty;
        this.categoryDetailed = categoryDetailed;
        this.comment = comment;
    }

    /**
     * Getter for <code>public.bank_transaction_classification.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for
     * <code>public.bank_transaction_classification.bank_transaction_id</code>.
     */
    public Long getBankTransactionId() {
        return this.bankTransactionId;
    }

    /**
     * Getter for
     * <code>public.bank_transaction_classification.category_fifty_thirty_twenty</code>.
     */
    public String getCategoryFiftyThirtyTwenty() {
        return this.categoryFiftyThirtyTwenty;
    }

    /**
     * Getter for
     * <code>public.bank_transaction_classification.category_detailed</code>.
     */
    public String getCategoryDetailed() {
        return this.categoryDetailed;
    }

    /**
     * Getter for <code>public.bank_transaction_classification.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BankTransactionClassification other = (BankTransactionClassification) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.bankTransactionId == null) {
            if (other.bankTransactionId != null)
                return false;
        }
        else if (!this.bankTransactionId.equals(other.bankTransactionId))
            return false;
        if (this.categoryFiftyThirtyTwenty == null) {
            if (other.categoryFiftyThirtyTwenty != null)
                return false;
        }
        else if (!this.categoryFiftyThirtyTwenty.equals(other.categoryFiftyThirtyTwenty))
            return false;
        if (this.categoryDetailed == null) {
            if (other.categoryDetailed != null)
                return false;
        }
        else if (!this.categoryDetailed.equals(other.categoryDetailed))
            return false;
        if (this.comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!this.comment.equals(other.comment))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.bankTransactionId == null) ? 0 : this.bankTransactionId.hashCode());
        result = prime * result + ((this.categoryFiftyThirtyTwenty == null) ? 0 : this.categoryFiftyThirtyTwenty.hashCode());
        result = prime * result + ((this.categoryDetailed == null) ? 0 : this.categoryDetailed.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BankTransactionClassification (");

        sb.append(id);
        sb.append(", ").append(bankTransactionId);
        sb.append(", ").append(categoryFiftyThirtyTwenty);
        sb.append(", ").append(categoryDetailed);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
