/*
 * This file is generated by jOOQ.
 */
package com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImportGroup implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String importSourceId;
    private final String importSourceType;

    public ImportGroup(ImportGroup value) {
        this.id = value.id;
        this.importSourceId = value.importSourceId;
        this.importSourceType = value.importSourceType;
    }

    public ImportGroup(
        Long id,
        String importSourceId,
        String importSourceType
    ) {
        this.id = id;
        this.importSourceId = importSourceId;
        this.importSourceType = importSourceType;
    }

    /**
     * Getter for <code>public.import_group.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.import_group.import_source_id</code>.
     */
    public String getImportSourceId() {
        return this.importSourceId;
    }

    /**
     * Getter for <code>public.import_group.import_source_type</code>.
     */
    public String getImportSourceType() {
        return this.importSourceType;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ImportGroup other = (ImportGroup) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.importSourceId == null) {
            if (other.importSourceId != null)
                return false;
        }
        else if (!this.importSourceId.equals(other.importSourceId))
            return false;
        if (this.importSourceType == null) {
            if (other.importSourceType != null)
                return false;
        }
        else if (!this.importSourceType.equals(other.importSourceType))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.importSourceId == null) ? 0 : this.importSourceId.hashCode());
        result = prime * result + ((this.importSourceType == null) ? 0 : this.importSourceType.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImportGroup (");

        sb.append(id);
        sb.append(", ").append(importSourceId);
        sb.append(", ").append(importSourceType);

        sb.append(")");
        return sb.toString();
    }
}
