/*
 * This file is generated by jOOQ.
 */
package com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.records;


import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankTransactionClassification;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankTransactionClassificationRecord extends UpdatableRecordImpl<BankTransactionClassificationRecord> implements Record5<Long, Long, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bank_transaction_classification.id</code>.
     */
    public BankTransactionClassificationRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bank_transaction_classification.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.bank_transaction_classification.bank_transaction_id</code>.
     */
    public BankTransactionClassificationRecord setBankTransactionId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.bank_transaction_classification.bank_transaction_id</code>.
     */
    public Long getBankTransactionId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>public.bank_transaction_classification.category_fifty_thirty_twenty</code>.
     */
    public BankTransactionClassificationRecord setCategoryFiftyThirtyTwenty(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.bank_transaction_classification.category_fifty_thirty_twenty</code>.
     */
    public String getCategoryFiftyThirtyTwenty() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public.bank_transaction_classification.category_detailed</code>.
     */
    public BankTransactionClassificationRecord setCategoryDetailed(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.bank_transaction_classification.category_detailed</code>.
     */
    public String getCategoryDetailed() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.bank_transaction_classification.comment</code>.
     */
    public BankTransactionClassificationRecord setComment(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.bank_transaction_classification.comment</code>.
     */
    public String getComment() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION.ID;
    }

    @Override
    public Field<Long> field2() {
        return BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION.BANK_TRANSACTION_ID;
    }

    @Override
    public Field<String> field3() {
        return BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION.CATEGORY_FIFTY_THIRTY_TWENTY;
    }

    @Override
    public Field<String> field4() {
        return BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION.CATEGORY_DETAILED;
    }

    @Override
    public Field<String> field5() {
        return BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION.COMMENT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getBankTransactionId();
    }

    @Override
    public String component3() {
        return getCategoryFiftyThirtyTwenty();
    }

    @Override
    public String component4() {
        return getCategoryDetailed();
    }

    @Override
    public String component5() {
        return getComment();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getBankTransactionId();
    }

    @Override
    public String value3() {
        return getCategoryFiftyThirtyTwenty();
    }

    @Override
    public String value4() {
        return getCategoryDetailed();
    }

    @Override
    public String value5() {
        return getComment();
    }

    @Override
    public BankTransactionClassificationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BankTransactionClassificationRecord value2(Long value) {
        setBankTransactionId(value);
        return this;
    }

    @Override
    public BankTransactionClassificationRecord value3(String value) {
        setCategoryFiftyThirtyTwenty(value);
        return this;
    }

    @Override
    public BankTransactionClassificationRecord value4(String value) {
        setCategoryDetailed(value);
        return this;
    }

    @Override
    public BankTransactionClassificationRecord value5(String value) {
        setComment(value);
        return this;
    }

    @Override
    public BankTransactionClassificationRecord values(Long value1, Long value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankTransactionClassificationRecord
     */
    public BankTransactionClassificationRecord() {
        super(BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION);
    }

    /**
     * Create a detached, initialised BankTransactionClassificationRecord
     */
    public BankTransactionClassificationRecord(Long id, Long bankTransactionId, String categoryFiftyThirtyTwenty, String categoryDetailed, String comment) {
        super(BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION);

        setId(id);
        setBankTransactionId(bankTransactionId);
        setCategoryFiftyThirtyTwenty(categoryFiftyThirtyTwenty);
        setCategoryDetailed(categoryDetailed);
        setComment(comment);
    }

    /**
     * Create a detached, initialised BankTransactionClassificationRecord
     */
    public BankTransactionClassificationRecord(com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.pojos.BankTransactionClassification value) {
        super(BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION);

        if (value != null) {
            setId(value.getId());
            setBankTransactionId(value.getBankTransactionId());
            setCategoryFiftyThirtyTwenty(value.getCategoryFiftyThirtyTwenty());
            setCategoryDetailed(value.getCategoryDetailed());
            setComment(value.getComment());
        }
    }
}
