/*
 * This file is generated by jOOQ.
 */
package com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.records;


import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.ImportGroup;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImportGroupRecord extends UpdatableRecordImpl<ImportGroupRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.import_group.id</code>.
     */
    public ImportGroupRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.import_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.import_group.import_source_id</code>.
     */
    public ImportGroupRecord setImportSourceId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.import_group.import_source_id</code>.
     */
    public String getImportSourceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.import_group.import_source_type</code>.
     */
    public ImportGroupRecord setImportSourceType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.import_group.import_source_type</code>.
     */
    public String getImportSourceType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ImportGroup.IMPORT_GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return ImportGroup.IMPORT_GROUP.IMPORT_SOURCE_ID;
    }

    @Override
    public Field<String> field3() {
        return ImportGroup.IMPORT_GROUP.IMPORT_SOURCE_TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getImportSourceId();
    }

    @Override
    public String component3() {
        return getImportSourceType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getImportSourceId();
    }

    @Override
    public String value3() {
        return getImportSourceType();
    }

    @Override
    public ImportGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ImportGroupRecord value2(String value) {
        setImportSourceId(value);
        return this;
    }

    @Override
    public ImportGroupRecord value3(String value) {
        setImportSourceType(value);
        return this;
    }

    @Override
    public ImportGroupRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImportGroupRecord
     */
    public ImportGroupRecord() {
        super(ImportGroup.IMPORT_GROUP);
    }

    /**
     * Create a detached, initialised ImportGroupRecord
     */
    public ImportGroupRecord(Long id, String importSourceId, String importSourceType) {
        super(ImportGroup.IMPORT_GROUP);

        setId(id);
        setImportSourceId(importSourceId);
        setImportSourceType(importSourceType);
    }

    /**
     * Create a detached, initialised ImportGroupRecord
     */
    public ImportGroupRecord(com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.pojos.ImportGroup value) {
        super(ImportGroup.IMPORT_GROUP);

        if (value != null) {
            setId(value.getId());
            setImportSourceId(value.getImportSourceId());
            setImportSourceType(value.getImportSourceType());
        }
    }
}
