/*
 * This file is generated by jOOQ.
 */
package com.ploter.budgetinsights.infrastracture.persistence.jooq.model;


import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankStatement;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankTransaction;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankTransactionClassification;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.ImportGroup;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.records.BankStatementRecord;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.records.BankTransactionClassificationRecord;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.records.BankTransactionRecord;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.records.ImportGroupRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BankStatementRecord> BANK_STATEMENT_PKEY = Internal.createUniqueKey(BankStatement.BANK_STATEMENT, DSL.name("bank_statement_pkey"), new TableField[] { BankStatement.BANK_STATEMENT.ID }, true);
    public static final UniqueKey<BankTransactionRecord> BANK_TRANSACTION_PKEY = Internal.createUniqueKey(BankTransaction.BANK_TRANSACTION, DSL.name("bank_transaction_pkey"), new TableField[] { BankTransaction.BANK_TRANSACTION.ID }, true);
    public static final UniqueKey<BankTransactionClassificationRecord> BANK_TRANSACTION_CLASSIFICATION_BANK_TRANSACTION_ID_KEY = Internal.createUniqueKey(BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION, DSL.name("bank_transaction_classification_bank_transaction_id_key"), new TableField[] { BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION.BANK_TRANSACTION_ID }, true);
    public static final UniqueKey<BankTransactionClassificationRecord> BANK_TRANSACTION_CLASSIFICATION_PKEY = Internal.createUniqueKey(BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION, DSL.name("bank_transaction_classification_pkey"), new TableField[] { BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION.ID }, true);
    public static final UniqueKey<ImportGroupRecord> IMPORT_GROUP_PKEY = Internal.createUniqueKey(ImportGroup.IMPORT_GROUP, DSL.name("import_group_pkey"), new TableField[] { ImportGroup.IMPORT_GROUP.ID }, true);
}
