/*
 * This file is generated by jOOQ.
 */
package com.ploter.budgetinsights.infrastracture.persistence.jooq.model;


import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankStatement;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankTransaction;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankTransactionClassification;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.ImportGroup;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.bank_statement</code>.
     */
    public final BankStatement BANK_STATEMENT = BankStatement.BANK_STATEMENT;

    /**
     * The table <code>public.bank_transaction</code>.
     */
    public final BankTransaction BANK_TRANSACTION = BankTransaction.BANK_TRANSACTION;

    /**
     * The table <code>public.bank_transaction_classification</code>.
     */
    public final BankTransactionClassification BANK_TRANSACTION_CLASSIFICATION = BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION;

    /**
     * The table <code>public.import_group</code>.
     */
    public final ImportGroup IMPORT_GROUP = ImportGroup.IMPORT_GROUP;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.BANK_STATEMENT_ID_SEQ,
            Sequences.BANK_TRANSACTION_CLASSIFICATION_ID_SEQ,
            Sequences.BANK_TRANSACTION_ID_SEQ,
            Sequences.IMPORT_GROUP_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BankStatement.BANK_STATEMENT,
            BankTransaction.BANK_TRANSACTION,
            BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION,
            ImportGroup.IMPORT_GROUP
        );
    }
}
