/*
 * This file is generated by jOOQ.
 */
package com.ploter.budgetinsights.infrastracture.persistence.jooq.model;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.bank_statement_id_seq</code>
     */
    public static final Sequence<Long> BANK_STATEMENT_ID_SEQ = Internal.createSequence("bank_statement_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.bank_transaction_classification_id_seq</code>
     */
    public static final Sequence<Long> BANK_TRANSACTION_CLASSIFICATION_ID_SEQ = Internal.createSequence("bank_transaction_classification_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.bank_transaction_id_seq</code>
     */
    public static final Sequence<Long> BANK_TRANSACTION_ID_SEQ = Internal.createSequence("bank_transaction_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.import_group_id_seq</code>
     */
    public static final Sequence<Long> IMPORT_GROUP_ID_SEQ = Internal.createSequence("import_group_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
