/*
 * This file is generated by jOOQ.
 */
package com.ploter.budgetinsights.infrastracture.persistence.jooq.model;


import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankStatement;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankTransaction;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.BankTransactionClassification;
import com.ploter.budgetinsights.infrastracture.persistence.jooq.model.tables.ImportGroup;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bank_statement</code>.
     */
    public static final BankStatement BANK_STATEMENT = BankStatement.BANK_STATEMENT;

    /**
     * The table <code>public.bank_transaction</code>.
     */
    public static final BankTransaction BANK_TRANSACTION = BankTransaction.BANK_TRANSACTION;

    /**
     * The table <code>public.bank_transaction_classification</code>.
     */
    public static final BankTransactionClassification BANK_TRANSACTION_CLASSIFICATION = BankTransactionClassification.BANK_TRANSACTION_CLASSIFICATION;

    /**
     * The table <code>public.import_group</code>.
     */
    public static final ImportGroup IMPORT_GROUP = ImportGroup.IMPORT_GROUP;
}
